### ISSUE TITLE
The roadmap of `vscode-bunn`

### ISSUE THREAD

**Issue by PlayerNguyen** [PlayerNguyen/vscode-bunn#3]
# Todo list
## Commands
- [ ] `Bun: Link npm dependencies globally` to run `bun link`
- [ ] `Bun: Install all dependencies` to install all dependencies from the current working workspace by determining the package.json
- [ ] `Bun: Add dependency` to add a new dependency
- [ ] `Bun: Start dev server` to run `bun dev` 

## Settings
- [ ] Add a setting to use an external terminal for commands

## Enhance
- [ ] Add CI test on Github actions
- [ ] Optimize the install / uninstall (if necessary)
